### ISSUE TITLE
Kerning Error

### ISSUE THREAD

**Issue by keylimepie44** [yuru7/HackGen#1]
When I try to install this font under macOS 10.14, I get an error about kerning.
The error message shows “kern table structure and contents”
This is a critical error and the font installation has been denied.
Plz fix it.

**Comment by chihiro-yamamoto** [comment]
me too.

macOS : 10.14.3

![image](https://user-images.githubusercontent.com/29139551/58165178-366b1d80-7cc2-11e9-83d5-cbd7d614e7a8.png)

**Comment by yuru7** [comment]
Thanks your report. I will investigate it.

By the way, can you use Japanese?  I'm not good at English.

英語でスマートに対応したいのですが、意思疎通に支障を来たすので日本語で対応いたします！すみません！

フォントの kern テーブルが Mac の仕様に合っていないようですね。調整してみます。

また残念なことに手元に Mac がないので、検証にご協力いただければ幸いです。

**Comment by yuru7** [comment]
ちなみにエラーが出てインストールできないのは、標準、太字、斜体、斜体太字すべてでしょうか？

**Comment by keylimepie44** [comment]
標準、太字、斜体、斜体太字すべてで同じエラーが発生しています

**Comment by yuru7** [comment]
情報ありがとうございます。

以下に、調整したバージョンのフォントを配置しました。こちらインストールできるかお試しいただけますか？

https://github.com/yuru7/HackGen/tree/kern_patch/build

**Comment by dora1998** [comment]
全書体、macOS Mojave 10.14.5にてそちらのビルドですとインストールできました。

**Comment by yuru7** [comment]
macOS Mojave 10.14.5 にてインストールできたとのことなので、このビルドを v0.1.1 としてリリースしました。
https://github.com/yuru7/HackGen/releases

皆さま、ご協力大変ありがとうございました！
