### ISSUE TITLE
Characters with accent marker not rendering properly

### ISSUE THREAD

**Issue by vSLG** [yuru7/HackGen#16]
## Description
Characters with accent marker are not rendering properly on HackGen and HackGenNerd.
I find this font cool and I would use it every day, but this issue is holding me back. As my native language (portuguese) has some special unicode characters, HackGen can't render them properly.
I don't understand how fonts work, but I haven't seen this issue on other fonts, so I assume it's a font specific problem.

## Environment
- OS: Void Linux, fontconfig is installed and working properly
- Terminal: Termite and Kitty
- Text editor: NeoVim and Visual Studio Code

## How to reproduce
- Write any text that contais latin characters/accent markers: ´ ` ~ ^ á à â ã ç é è ê ẽ, etc
- Font shows unexpected behavior

| On terminal (NeoVim) | On Visual Studio Code |
| --- | --- |
| ![2020-08-02 15:44:45-screenshot](https://user-images.githubusercontent.com/38402340/89130079-88b7e900-d4d8-11ea-98b8-94289b057f94.png) | ![2020-08-02 15:58:54-screenshot](https://user-images.githubusercontent.com/38402340/89130162-1d224b80-d4d9-11ea-8cb9-85d8318fd9d6.png) |

Text used:
normal
nórmâl

car
çar

## Expected behavior
Font renders correctly, with characters with accent marker having same width as other characters.

**Comment by yuru7** [comment]
Thanks for the report.

First of all, I'm not very good at English, so I apologize if I didn't convey my intentions well.

Basically, HackGen is made for Japanese, so I can't guarantee that it will be displayed in any other language.

But I think you can solve this problem by changing the font family you use.

Try changing your font family from "HackGen" to "HackGen Console".

|"HackGen" v2.1.1 on Visual Studio Code|"HackGen Console" v2.1.1 on Visual Studio Code|
|---|---|
|![image](https://user-images.githubusercontent.com/13458509/89133463-f9054f80-d556-11ea-967f-3476cdc8f4ab.png)|![image](https://user-images.githubusercontent.com/13458509/89133475-1508f100-d557-11ea-8c21-488f9dc6044c.png)|

**Comment by vSLG** [comment]
Thanks! It works now.
