### ISSUE TITLE
NerdFontに欠落

### ISSUE THREAD

**Issue by tani** [yuru7/HackGen#19]
こんにちは。素晴らしいフォントをありがとうございます。

## 環境

- OS: Linux (Kubuntu 20.04)
- ソフトウェア: Konsole 19.12.3
- 対象フォント: HackGen35Nerd, HackGen35Nerd Console, HackGenNerd, HackGenNerd Console
- 比較対象フォント: FiraCode Nerd Font

## 事象

`喝(fa36)`に対応するグリフを表示させたところ、他のNerd Fontでは`△`と表示されるのに対して、HackGenNerdでは`喝`が表示されました。

## 考察

Nerd Fontsのパッチを当てる際にオリジナルのHackGenにあるグリフが優先され、
Nerd Fontsのグリフが欠落している可能性があります。

## 要望

HackGenと HackGen ConsoleのようにNerd Fontsについても、オリジナルとNerd Fontsのグリフのどちらを優先するか選択肢をユーザーに委ねるようにしていただきたいです。

**Comment by yuru7** [comment]
ご報告ありがとうございます。
事象が確認できました。

ご報告の `U+FA36` を含む [CJK互換漢字](https://ja.wikipedia.org/wiki/CJK%E4%BA%92%E6%8F%9B%E6%BC%A2%E5%AD%97) の範囲等で、Nerd Fonts のグリフが破棄されているようです。

これは源柔ゴシックに含まれるグリフが優先して合成されているために起きているようです。

これを回避するのであれば、ご要望のように別立てで Nerd Fonts が全て含まれるパターンのフォントファミリーを提供する必要があると考えます。

ちょっと検討してみます。

**Comment by called-d** [comment]
Nerd Fonts の 3.0 で修正される https://github.com/ryanoasis/nerd-fonts/issues/365 というやつですね

**Comment by tani** [comment]
@called-d さん，お教えくださりありがとうございます．これは，うれしい更新ですね．Nerd Fonts 3.0がリリースされれば，統合漢字も絵文字も使えるようになって便利そうです．ただ，コードポイントが大きく変わることになるので，しばらくは互換性の問題で苦労しそうです．

@yuru7 さん，https://github.com/yuru7/HackGen/commit/6f2e10da6116ae1adf39c6f369b6a761d89f1df4 のコミット内容を拝見いたしました．修正ありがとうございます．こちらの修正が入ったフォントがリリースされたら，こちらのIssueを閉じてもよいのですが， @called-d さんからの情報も含めるとNerd Fonts 3.0がリリースされてそちらが適用されるまでは，こちらのIssueは開いておきたいと思います．いかがでしょうか？

**Comment by yuru7** [comment]
> @yuru7 さん，6f2e10d のコミット内容を拝見いたしました．修正ありがとうございます．こちらの修正が入ったフォントがリリースされたら，こちらのIssueを閉じてもよいのですが， @called-d さんからの情報も含めるとNerd Fonts 3.0がリリースされてそちらが適用されるまでは，こちらのIssueは開いておきたいと思います．いかがでしょうか？

ご確認ありがとうございます。
当該コミットログにもある通り、以降のHackGenNerdではNerd Fontsを優先しようと考えています。従って、一部の漢字はNerd Fontsのグリフに置き換えられるのが仕様となります。

さて、Nerd Fonts 3.0が出るまでIssueを開いていては、との提案ですが、こちらは次のリリース次第、クローズしようと考えています。最新のNerd Fonts 2系における「Nerd Fontsが全て適用されていない」という主題は解消されていて、それ以外の「Nerd Fonts 3.0への追従」などのタスクを含めたくないためです。

既にNerd Fontsエコシステムとも言えるほど増えた様々なツール群が、コードポイントが変更されてしまったNerd Fonts 3.0に果たしてどれくらい追従するのか、といった問題が出てくることでしょうから、そうなったときにHackGenもどう対応していくかを改めて考えます。

**Comment by tani** [comment]
@yuru7 Nerd Fontsの絵文字が互換漢字より優先される方針とのことで承知しました．
ご指摘の通りNerd Fonts 3.0に追従することと，絵文字の欠落は別の課題ですね．
では，次期HackGenがリリースされた暁にはこちらのIssueを閉じていただいて構いません．
宜しくお願い致します．

**Comment by yuru7** [comment]
本修正を取り込んだ [v2.4.0](https://github.com/yuru7/HackGen/releases/tag/v2.4.0) をリリースしましたので、クローズします。ご報告ありがとうございました🙇‍♂️

**Comment by tani** [comment]
ありがとうございます！
