### ISSUE TITLE
`{}` の上下位置がずれている

### ISSUE THREAD

**Issue by yuru7** [yuru7/HackGen#20]
VSCode上で`{}`が下のようにずれて表示されてしまっています。

![image](https://user-images.githubusercontent.com/15074382/100516336-94859480-31c6-11eb-80be-c320102f0bda.png)

### 環境

OS: Windows 10 Pro ビルド19041
VSCode: 1.51.1
ディスプレイ: 1920x1080

### VSCode設定

![image](https://user-images.githubusercontent.com/15074382/100516405-fb0ab280-31c6-11eb-801f-a6db8366899e.png)

_Originally posted by @ssssota in https://github.com/yuru7/HackGen/issues/10#issuecomment-735229768_

**Comment by yuru7** [comment]
@ssssota
私の環境では気になっていなかったのですが、フォントサイズによってはズレが目立つようになることが分かりました。

調査したところ、合成元の Hack フォントの Regular サイズで、`{` よりも `}` のほうが数ポイント下にずれていることが分かりました。(Bold はずれていない)
これを修正したものを、下記にアップしました。一旦こちらを試してみていただけますか？
https://github.com/yuru7/HackGen/tree/dev/build

**Comment by ssssota** [comment]
早速の対応ありがとうございます。

先述の環境で確認しましたところ、
`HackGen`フォント指定時は修正されて ![image](https://user-images.githubusercontent.com/15074382/100530546-cdf5e880-3236-11eb-94fc-39764f335b22.png) 揃っておりましたが、
`HackGenNerd`フォント指定時は、前バージョン同様 ![image](https://user-images.githubusercontent.com/15074382/100530565-fda4f080-3236-11eb-8f52-a602fa7911d6.png) ずれておりました。

**Comment by yuru7** [comment]
それは奇妙ですね…
こちらでも `HackGen` と `HackGenNerd` で確認してみましたが、いずれもズレは修正されていました。

もしかして `HackGen` は今、新規にインストールして、 `HackGenNerd` の方は上書きインストールしませんでしたか？その場合、表向きインストールできているようで、実はうまくいっていない可能性があります。

これは Windows のフォントインストールの悪癖のようなもので、上書きインストールを繰り返していると、内部的に古いフォントファイルを引きずる場合があります。(私もよく遭遇します)

一旦以下の手順を試してみてください。

1. Windows 再起動 (フォントファイルを掴んでいるプロセスを無くしたいため)
2. 再起動直後、 `C:\Windows\Fonts` を開いて、そこから `HackGenNerd` を削除する
3. `%userprofile%\AppData\Local\Microsoft\Windows\Fonts` を開き、もしその中に `HackGenNerd` フォントがあるようであれば、削除する
4. Windows を再起動し、`HackGenNerd` フォントをインストールする

**Comment by ssssota** [comment]
> これは Windows のフォントインストールの悪癖のようなもので、上書きインストールを繰り返していると、内部的に古いフォントファイルを引きずる場合があります。(私もよく遭遇します)

知りませんでした…

お手数おかけして申し訳ありません。
`HackGenNerd`フォントについても ![image](https://user-images.githubusercontent.com/15074382/100566989-cc95f000-330a-11eb-8fa3-97383095b3ba.png) 揃っていることが確認できました。

**Comment by yuru7** [comment]
ご確認ありがとうございます。
細かいところではありますが、おかげで気付きづらい不具合を解消できたと思います。
ご報告ありがとうございました😃

**Comment by yuru7** [comment]
当修正を取り込んだ v2.2.2 をリリースしました。
