### ISSUE TITLE
HackGen Nerd Console の矢印が半角になっている

### ISSUE THREAD

**Issue by kottn** [yuru7/HackGen#25]
HackGen Nerd Console の全角矢印が半角分に収まっているのは、仕様でしょうか？
Console 版も矢印は全角で統一したほうが、日本語を書くときには揃って良さそうだな、と思って立ててみました。

![image](https://user-images.githubusercontent.com/35750723/115829284-c6371a80-a449-11eb-8099-9ff0e518f5d3.png)

以前使っていたいくつかの等幅フォントの矢印がすべて全角だったため、違和感を感じたのですが、
こだわりや仕様ということであれば大変失礼しました。

いつも使わせてもらっています、開発ありがとうございます。

**Comment by yuru7** [comment]
ご愛用ありがとうございます。

矢印記号について、これは仕様です。

ご認識されているかもしれませんが、Console版はその名の通り「コンソールでの利用に便利な仕様」を目指しています。
そのためConsole版では「源柔ゴシックとHackフォントに両方に含まれる文字の場合、Hackフォントの方の文字 (半角文字) を優先する」ようにしています。これは、コンソールのアプリによっては、特定の記号を半角で扱わないとカーソルの位置がずれる等の不具合が起こるためです。
そして、Hackフォントには多くの記号類も収録されており、矢印記号もその1つです。そのために半角表示となっています。

したがって、心苦しいですがこの要望にお応えすることはできません。

Console版でない通常版であれば、前述した「源柔ゴシックとHackフォントに両方に含まれる文字の場合」の優先度が、源柔ゴシックが優先されるようになります。そのため、矢印記号を含む多くの記号が全角で表示されます。テキストエディタでは通常版を利用するなど、状況に応じて利用する方法をご検討いただければと思います。

**Comment by kottn** [comment]
なるほど理解しました。フォント関係は全く素人なもので、勉強になりました。ご丁寧に説明いただきありがとうございました。
