### ISSUE TITLE
文字間が少し広い

### ISSUE THREAD

**Issue by hitobashira** [yuru7/HackGen#28]
セルスペーシングというか、文字間が少し広いのではないでしょうか。
比較対象、Ricty,NASU です。

ubuntu 20.04
manjaro 21.0.7

どのターミナルでも同様。

- gnome-terminal 
- tilix
- terminator

HackGenNerd です。

**Comment by yuru7** [comment]
ご報告ありがとうございます。
まず確認をさせてください。

これは、テキストエディタ上だと問題ないが、ターミナルアプリ上だと文字間が広がる場合があるといった問題報告でしょうか？

それとも、どのアプリ上であっても文字間が広く見えるから見直してほしい、といった文字レイアウト上の修正提案でしょうか？

**Comment by yuru7** [comment]
以下で確認してみましたが、特段、文字間が広くなるといった不具合は無いように見えます。
（純粋なUbuntu環境で確認する時間は無かったため、取り急ぎ Kubuntu+Konsole で確認）

- Kubuntu 20.04  
- Konsole
- HackGen 2.3.5

|`Ricty Diminished`<br/>size 12pt|`HackGenNerd`<br/>size 11pt|
|:---:|:---:|
| ![Screenshot_20210622_055911](https://user-images.githubusercontent.com/13458509/122830366-34ea0480-d323-11eb-801f-f528f088d97e.png) | ![Screenshot_20210622_060033](https://user-images.githubusercontent.com/13458509/122830379-39162200-d323-11eb-86d0-5cc20fe58e36.png) |

**Comment by hitobashira** [comment]
当方の環境依存ですか。うーん。
念のため、どう見えているのか、gnome-teriminal をキャプチャしてみます。
「スライム」の行がわかりやすいかと思います。

- 黒背景がmig1m
- 白背景がhackgen nerd 


![2021-06-23_00-20](https://user-images.githubusercontent.com/12706780/122952741-2c440d80-d3b9-11eb-9725-55b778dffa03.png)

Linux Mint 20.1
※全体に文字はかなり大きめです。UHD4Kです。

**Comment by yuru7** [comment]
なるほど、状況が見えてきたかもしれません。

まずフォントの表示において下記の前提があります。

- フォントの幅、高さはフォント毎に異なる
- サイズ (12pt や 18pt など) 毎に実際の画面上でどれくらいの大きさで描画されるかもフォント毎に異なる

したがって、同じ 18pt であっても、表示上の幅（文字間）や高さ、あるいは文字サイズが変わってくることはあり得ます。
そして、Ricty と HackGen に関してはこれらに関わる設定が異なるため、同じ文字サイズ、例えば hitobashira さんのように両方を 18pt に設定すると、高さ、幅、表示サイズが変わってきます。これは正常な動きです。 (ちなみに Ricty と Migu1M に関しては、これらの高さや幅の設定が同じようですので、自然と幅なども同じように揃うと思います。)

また HackGen に関しては比率 1:2 幅へ変形する際に Hack の文字の横幅を狭めすぎないよう、全角文字側の幅を少し広めに取る処置を加えています。そのため HackGen35 と比べると全角文字同士が少し離れて見えるかもしれません。

以上のことから、本件に関しては不具合ではないと判断します。
Ricty などと幅を揃えたいということでしたら、ディスプレイ解像度やアプリに応じて、HackGen や HackGen35 を切り替えたり、文字サイズを 1pt ほど上下させるなどして調節することをオススメいたします。
