### ISSUE TITLE
Visual StudioのEditer全角表示に対応したい

### ISSUE THREAD

**Issue by XinViet** [yuru7/HackGen#35]
その他のEditor 例えば sakura Editorなどはhackgenにfontを変更すると全角スペースがきちんと表示されるのですが
Visual StudioのEditorでは全角スペースが表示されないのですが
Visual Studioの設定で何とかなるのでしょうか？

**Comment by yuru7** [comment]
@XinViet 
確認が遅くなってしまい、すみません。

エディタによって、全角スペースをフォント側の表示に委ねずにエディタ独自の表示になるケースはあり得ます。例えば、私が使う環境の中では、Eclipseでは正しく表示できませんでした。そういった場合には、エディタ側の設定やアドオンなどを使って、全角スペースを見分けられるようにする他ないと思います。

残念ですが、各エディタについての設定についてはサポートできません。お力になれず恐縮ですが、全角スペースを表示するための設定がないか調べていただければと思います。
