### ISSUE TITLE
Pomiconsを使えるようにしてほしい

### ISSUE THREAD

**Issue by takumadnl** [yuru7/HackGen#39]
少し前にPomiconsのライセンスが`SIL Open Font License 1.1`に変更されました。
商用でも利用できるようなので、白源で使えるようにしてほしいです。

https://github.com/gabrielelana/pomicons/blob/master/LICENSE

**Comment by yuru7** [comment]
v2.6.4にて対応しました。

情報ありがとうございました🙇‍♂️
