### ISSUE TITLE
太字の`プ`が細い

### ISSUE THREAD

**Issue by ozelotjp** [yuru7/HackGen#4]
`HackGen35-Regular v1.2.0`を使用しています。
太字の **フ** と **プ** を比べると、**プ** が細くなっています。

（右上の`プ`です）
![](https://user-images.githubusercontent.com/32789856/61929922-59ae9380-afb7-11e9-9921-d09effe0b87e.png)

通常版（`HackGen-Regular v1.2.0`）の方では太さは正常でしたので、
恐らくHackGen35限定の問題だと思います。

**Comment by yuru7** [comment]
@ozelotjp さん
ご報告ありがとうございます。

当方の環境 (Win 10 x64) でもいくつかのテキストエディターで確認してみましたが、ご申告のような表示は確認できませんでした。

どのような環境 (OS, エディター等) で使用した結果でしょうか？また、他のエディターでも同様の表示でしょうか？ 

ちなみに一例として、以下は VSCode で文字サイズ 80pt にした HackGen35 の表示です。

![image](https://user-images.githubusercontent.com/13458509/61991045-c6905f00-b085-11e9-88ac-e51e589a6258.png)

**Comment by yuru7** [comment]
@ozelotjp さん
おそらく同じ状況が再現できました。

![image](https://user-images.githubusercontent.com/13458509/61991353-c1cdaa00-b089-11e9-90d8-a418a13cfea5.png)

こちらで確認した条件は以下の通りです。

* Win 10 x64 VSCode (DirectWrite レンダリング)
* HackGen Regular のみをインストールし、Bold はインストールしない
* VSCode のシンタックスハイライトで、「プ」を太字表示にする

VSCode ではシンタックスハイライトで太字や斜体を表示しようとする際、表示中のフォントファイルに太字／斜体がインストールされていなくても勝手にそれらしい表示を生成してくれる機能があります。
例えば、HackGen ファミリーには斜体が含まれていませんが、VSCode 上では上記機能によって斜体表示が可能です。

この機能によって太字を表示すると、何故か「プ」の表示が上記キャプチャーのように崩れるようです。
ただしこれはあくまでも、該当するスタイルのフォントがインストールされていないときの動作であるため、Bold フォントがインストールされていれば VSCode はそちらを表示するため、正常な表示となります。

これと同じ原因であれば、Bold 書体もインストールすると解消されるかと思います。

**Comment by ozelotjp** [comment]
@yuru7 さん

Win 10 x64 VSCode (DirectWrite)を使用しています。
仰っていた通り、HackGen35 Regularのみインストールしていました。

> これと同じ原因であれば、Bold 書体もインストールすると解消されるかと思います。

Bold書体をインストールしたところ、太字の「プ」も正常に表示されました。
ご対応ありがとうございました！
