### ISSUE TITLE
codiconsに対応して欲しい

### ISSUE THREAD

**Issue by yuys13** [yuru7/HackGen#40]
HackGen Console NF(v2.7.1)を常用しております。
見やすいフォントをたくさん作っていただき、ありがとうございます。
この度nerdfontを要求する端末アプリを利用していたところ、`ead1`など一部のフォントが表示されないことに気付きました(hackのnerdfont等では表示されました)。
フォントには疎いのですが、codiconsが含まれていないものと推測しております。
HackGenにcodiconsが含まれていると嬉しいのですが、歴史的経緯やツールの制約等で難しい問題なのでしょうか？

**Comment by yuru7** [comment]
ご報告ありがとうございます。
codiconsがNerdFontsに加わったのは、今年の8月頃のようですね。HackGenに利用しているNerdFontsはそれより前のバージョンであったため、含まれていないようです。
次のリリースに組み込めるようにしてみます。

**Comment by yuys13** [comment]
ご回答ありがとうございます。
なるほど、NerdFontsも更新されているのですね。そこまで考えが至りませんでした。
確かにGitHubのreleaseを確認してみたところ、v2.2.0でcodiconsに対応しているようですね。
次回リリース時に考慮していただけるとのことで、ありがたく思います。

**Comment by yuru7** [comment]
v2.8.0 リリースに組み込みました！ご報告ありがとうございました。

**Comment by yuys13** [comment]
v2.8.0で表示確認できました！「次のリリース」が驚きの速さでした 🚀 
ご対応ありがとうございました！！
