### ISSUE TITLE
合成元フォントのライセンスに反している部分がある

### ISSUE THREAD

**Issue by yumunet** [yuru7/HackGen#41]
合成元のフォント（源柔ゴシック、Hack、NerdFonts）のライセンスに沿っていないと思われる部分です。
ご確認いただけると幸いです。

1. 配布物に合成元フォントのライセンスが含まれていない
源柔ゴシックやNerdFontsのSIL Open Font License 1.1や、HackのMIT LicenseとBITSTREAM VERA LICENSEには著作権表示に加えライセンスも含めるように記載があります。
ライセンスのファイル3つすべてをリリース時に入れるか、ttfに埋め込むと良いと思います。

2. ttfに埋め込まれたHackの著作権表示に、Bitstream Veraの著作権が含まれていない

3. sourceディレクトリ下にNerdFontsのライセンスが存在しない

**Comment by yuru7** [comment]
> 1. 配布物に合成元フォントのライセンスが含まれていない
源柔ゴシックやNerdFontsのSIL Open Font License 1.1や、HackのMIT LicenseとBITSTREAM VERA LICENSEには著作権表示に加えライセンスも含めるように記載があります。
ライセンスのファイル3つすべてをリリース時に入れるか、ttfに埋め込むと良いと思います。

本リポジトリにおいてソースコードを含めたすべてが配布物であり (Releases の各バージョンタグからその時点のリポジトリ全量もすぐにダウンロードできる) 、その中にライセンスファイルという形で提示しているため、「ライセンスが含まれていない」というのは誤りと考えます。(後述の通り、NerdFontsについてはライセンスファイルをリポジトリ内に含めるのが漏れていましたが…)
したがって、最低限の要件としての「著作権表示およびライセンスを含める」というのはライセンスファイルでの提示により満たしていると考えています。

ただし、リリース時のzipに入れるか、ttfファイル内に著作権・ライセンス表示を含めるのは "より" 望ましく親切であるという点には同意します。次回リリースから同梱することを検討します。

> 2. ttfに埋め込まれたHackの著作権表示に、Bitstream Veraの著作権が含まれていない

前述のとおり、ライセンスファイル (https://github.com/yuru7/HackGen/blob/master/source/LICENSE_Hack) にてまずは提示できているため、ttf埋め込みはより望ましい対応の範疇かと考えます。ただ、あえて含めない理由も無いので、次回リリースから含めようと思います。

> 3. sourceディレクトリ下にNerdFontsのライセンスが存在しない

ライセンスファイルの追加が漏れていました。以下で追加しました。
Commit: 764361d6c195d7cea0c02685aabe6d3e0e419fa5

ご指摘ありがとうございました。

**Comment by yumunet** [comment]
ご対応ありがとうございます！

1について、「配布物」というのは「HackGen_v2.8.0.zip」や「HackGen_NF_v2.8.0.zip」のことのみを指す意味で使いました。
ソースコードにライセンスファイルが含まれているのは分かるのですが、ソースコードとは別に配布している前述のフォント本体のzip内にライセンスが含まれていないのはどうなのだろうという意図でした。
ですが確かにライセンスを含めたソースコードをGitHubで公開してそこで配布もしているわけですから、「ライセンスに反している」とまではいかなかったかもしれませんね。見方次第なのでしょうか。
