### ISSUE TITLE
ターミナル上でギリシャ文字入力時にカーソル位置がずれる

### ISSUE THREAD

**Issue by mashiton** [yuru7/HackGen#42]
Hackgen を使って Windows Terminal上でギリシャ文字を入力すると、それ以降のカーソルの表示位置がずれてしまいます。

\>αβγ12345

と入力した場合、カーソル表示が「3」の位置になってしまいます。（その場合でも新たに入力される位置は「5」の右隣）
また、CUI版の vim/nvim でも同じ現象が起こりますが、GUI版vim/nvimやメモ帳では問題はありませんでした。
以下、いくつかのフォントで試してみた結果です
ｘ Hackgen v2.8.0
ｏ Hackgen Console NFJ v2.8.0
ｘ PlemolJP v1.4.0
ｘ PlemolJP Console NFJ v1.4.0

windows 10 Home 21H2
windows terminal 1.16.10261.0
Powershell 7.2.9
vim kaoriya 8.2 
nvim 0.8.3

**Comment by yuru7** [comment]
これは、フォントを表示するソフトウェアが一部の文字の幅をフォント内で定義されている幅を無視してしまうことに起因しています。この問題は割りとポピュラーなものなので、ご興味があれば「East Asian Ambiguous Width コンソール」などのキーワードで調べてみてください。

ご報告のとおり、Windows Terminalでもこの問題が起きていることを確認しました。Windows Terminalの挙動から察するに、Windows TermianalではEast Asian Ambiguous Widthに当てはまる文字を半角幅とみなして、カーソル位置を計算しているものと思われます。ただし挙げていただいたフォントのなかでHackGen Console NFJだけは `αβγ` が半角幅のグリフとなっているため、この問題を回避できているようです。

East Asian Ambiguous Width問題は、以下のいずれかで対処するしかありません。

1. 不具合の起こりづらい (＝East Asian Ambiguous Widthに当てはまる文字が半角幅になっている) フォントを使う
2. East Asian Ambiguous Width問題の起きないソフトウェアを使う
3. East Asian Ambiguous Width問題というものがあるのだな、と割り切って目を瞑る

日本語利用を第一に想定したソフトウェアはこのあたりの挙動は敏感に対処されている印象ですが、ターミナルのような英語利用が基本となるものは全角文字の優先度は下がるためEast Asian Ambiguous Width問題が起きやすいです。

**Comment by mashiton** [comment]
フォントではなくアプリケーション側のポピュラーな問題だとは知らず失礼しました。
PlemolJPが正しく表示されないのは残念ですが Hackgen Console NFJ を引き続き使わせていただきます。
詳細な説明をありがとうございました。

**Comment by yuru7** [comment]
@mashiton  PlemolJP Console v1.5.0 にて、一部の曖昧幅記号を半角にしてみました。以前より本件関連の問題は起きづらくなったかと思います。よかったら試してみてください。

**Comment by mashiton** [comment]
対応してくださってありがとうございます。早速使わせてもらいます。
