### ISSUE TITLE
サロゲートペアで表されるNerdFontの文字が豆腐になる

### ISSUE THREAD

**Issue by yuma140902** [yuru7/HackGen#43]
`󰊕 f0295 (nf-md-function)`などの、サロゲートペアで表されるNerdFontの文字が豆腐になってしまいます。
nerdfont.comで配布されているHack Nerd Fontなど、他のNerd Fontでは正しく表示されるようです。

## 環境

OS: Windows 11
フォント: HackGen Console NF、HackGen Console NFJ、HackGen35 Console NF、HackGen35 Console NFJ、いずれもv2.8.0
ソフトウェア: Windows Terminal 1.16.10262.0、Mery 3.3.5

**Comment by yuru7** [comment]
ご報告ありがとうございます。
現在のHackGenの生成スクリプトでは、 https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points に記載の領域のグリフをマージするようにしていますが、どうやらそれ以外にもNerdFontsで拡張されているグリフが存在するようですね。
上記のWikiが完全でない以上は、 `Hack オリジナル ⇔ NerdFontsパッチ後 Hack` とのグリフ差分を取ってそれを適用するなど、別の処方が必要になりそうです。

**Comment by yuma140902** [comment]
調べてみたのですが`f0295`は<https://github.com/ryanoasis/nerd-fonts/pull/773>で追加されたグリフのようです。Nerd Fonts 3.0へのアップデートの一貫として<https://github.com/ryanoasis/nerd-fonts/issues/365#issuecomment-1022906071>の「Plan 5」を実装したようです。仰る通り現時点ではwikiが不完全になっていますが、Nerd Fonts 3.0がリリースされた時点で更新されるのではないかと思います。

以前どこかで3.0への対応は改めて考えると仰っていたと思いますので、このissueは閉じてしまっても構いません。

**Comment by yuru7** [comment]
なるほど。一部のCJK文字との衝突を避けるためのアップデートの布石ということですね。過渡期としての対応なのでしょうね。
HackGenとしては、NerdFonts側の仕様が固まってから取り込みたいので、本件は少なくともNerdFonts 3.0 以降での対応がいいかと考えています。

情報提供ありがとうございました。
