### ISSUE TITLE
[✔]はUnicodeの東アジアの文字幅は半角ですので Console フォントでは半角幅で表示される必要があります

### ISSUE THREAD

**Issue by tomoyan596** [yuru7/HackGen#44]
こんにちは😊

いつも素晴らしいフォントを使わせて頂きありがとうございます🙇‍♂️

[✔]がHackGen Console NFJで全角幅で表示される事に気が付きました🤔
しかし、これはUnicodeの東アジアの文字幅では半角幅の扱いです。
![IMG_20230407_001317](https://user-images.githubusercontent.com/3541130/230422798-c0c1da8c-2d35-4e1d-8e30-15ccb0100f2a.jpg)
![IMG_20230407_001323](https://user-images.githubusercontent.com/3541130/230422759-5e7ca50a-9a10-4b5a-8917-768b625d7bb0.jpg)

これは修正する必要があると思われますが、開発者さんのご意見をお聞きしたいと思いましたので、まずはご報告いたします。

**Comment by yuru7** [comment]
ご報告ありがとうございます。
これは不具合ではなく、現状のHackGen仕様となります。

HackGenでは、ご存知の通り、Hackフォントと源柔ゴシックを合成しています。そして、通常版・Console版の違いは、「Hackフォントと源柔ゴシック両方で含まれているグリフの場合、どちらを優先するか」という点にあります。Console版はHackフォントの記号をすべて優先するために多くの記号が結果的に半角幅 (Hackフォントの幅) となります。
ところが、Hackフォントには `✔` というグリフが含まれていません。従って、通常版・Console版を問わず、 `✔` は源柔ゴシックに含まれているもの (これが全角の記号となっている) が適用されています。

**Comment by tomoyan596** [comment]
ご説明ありがとうございます。
現状のHackGen仕様とのことで認識しておくことにします。

余談ですがLinuxターミナルでは`✔`がHackGen Consoleフォントで半角扱いされなくても、出力が崩れたりはしていません。
![image](https://user-images.githubusercontent.com/3541130/231039644-a76b794f-efd7-4175-be45-dec41c8c7bff.png)

Webベースの開発系アプリではコンソール出力に`DejaVu Sans Mono`フォントが強制されており、monoフォント系は`✔`を半角表示しています。
![image](https://user-images.githubusercontent.com/3541130/231038507-ea0d1fdf-1bef-4b93-b4e9-046d89aea051.png)

コンソール出力結果をエディタに持っていくと、エディタは`✔`をHackGen Consoleフォントで全角表示しますので、枠が崩れるものが出てきます。
![image](https://user-images.githubusercontent.com/3541130/231038801-bfa56519-06ec-4b5e-b4ba-b2ef0a0636c5.png)

エディタで`✔`が全角表示扱いされて困ることは稀だとは思われますが、もしも半角表示で扱わなければならない様な場面では、現状では`DejaVu Sans Mono`フォントなどの半角表示してくれるフォントで扱うことにします。
![image](https://user-images.githubusercontent.com/3541130/231038909-91bc6a97-d001-45d2-916d-35a15bdc1746.png)

今後もHackGenフォントを愛用していきたいと思います。
作者の方々に感謝いたします。
ありがとうございました。
