### ISSUE TITLE
リリースパッケージにHackGenとHackGen35用のNerd FontsのTTFファイルがない

### ISSUE THREAD

**Issue by TJ-Hidetaka-Takano** [yuru7/HackGen#46]
v2.6.4以前のパッケージには
Reguler/Bold違い、文字幅比率違い(35有無)、Console用の有無、Nerd Fontsの有無で、
2 x 2 x 2 x 2 = 16 本のTTFファイルがありましたが、
v2.7.0以降には12本しかありませんでした。
恐らく、

* HackGenNF-Regular.ttf
* HackGenNF-Bold.ttf
* HackGen35NF-Regular.ttf
* HackGen35NF-Bold.ttf

が含まれるものかと思いますが、何か除外している理由があるのでしょうか？🤔

**Comment by yuru7** [comment]
反応遅くなってしまってすみません。

はい、v2.7.0 からNerd Fonts合成はConsole系統のみに限定しています。
https://github.com/yuru7/HackGen/releases/tag/v2.7.0

上記リリースに一言書いてはありますが、理由までは言及していなかったですね。混乱させてしまったようで申し訳ありません。

理由としては、Nerd Fontsはコンソール（ターミナル）での利用が大半を占めると思われ、となるとConsole版のみの提供でニーズを満たせると考えたためです。

通常版はAmbiguous Widthに分類される記号類の多くが全角幅で表示されるため、ターミナルアプリによってはカーソル位置ズレなどの問題を引き起こしますしね。

以上の理由と、必要最低限の提供にした方がメンテ負荷は下がる点から、リリースから除く判断をしました。

**Comment by TJ-Hidetaka-Takano** [comment]
返答ありがとうございます。
v2.7.0のリリース文を読み漏らしていました。🙇🏻‍♂️
そういう判断があったのですね。
テキストファイルでNerd Fonts含めて記号が全角のままで使えて便利でしたが、
了解いたしました。

本件closeいたします。
