### ISSUE TITLE
大型括弧の縦位置がずれる

### ISSUE THREAD

**Issue by naohaq** [yuru7/HackGen#50]
`U+239B` ⎛ ～`U+23AE` ⎮ の一連のグリフが、縦方向にずれています。
`ttfautohint`の結果として起きるようで、 `hackgen_generator.sh` の`select_evacuate_from_hinting`変数に

`  SelectMore(0u239b, 0u23ae)`

という記述を追加すると改善されます(1枚目の画像がずれた状態、2枚目の画像が改善後)。

![parentheses_corrupt](https://github.com/user-attachments/assets/d93e7d38-4700-40cd-a3a1-eedc6131b938)
![parentheses_normal](https://github.com/user-attachments/assets/89a9b9df-31fc-4ebf-97ae-9debf9446bc9)

**Comment by yuru7** [comment]
詳細なご報告、ありがとうございます！
再現確認でき次第、修正します。

**Comment by yuru7** [comment]
ご報告ありがとうございました。
https://github.com/yuru7/HackGen/releases/tag/v2.9.1 にて、修正版をリリースしました。
