### ISSUE TITLE
Update Nerd Fonts to v3.3.0

### ISSUE THREAD

**Issue by 5ouma** [yuru7/HackGen#51]
Since [v3.3.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.3.0) introduced many icons via [devicons/devicon](https://github.com/devicons/devicon).

**Comment by yuru7** [comment]
ありがとうございます。
HackGen v2.10.0 にて、Nerd Fonts v3.3.0 を取り込みました。
https://github.com/yuru7/HackGen/releases/tag/v2.10.0
