### ISSUE TITLE
tree や pstree の表示が崩れる

### ISSUE THREAD

**Issue by huyu398** [yuru7/HackGen#7]
## 現象
`tree` や `pstree` を実行すると，「┬」や「├」や「└」でツリー表示されるが，これらの表示が崩れる．
![pstree結果](https://user-images.githubusercontent.com/4333569/65930198-dd658000-e43f-11e9-908a-ee895f32756a.png)

Windows 標準のフォントプレビューで確認しても，表示が崩れているのが確認できる．
![─┬─](https://user-images.githubusercontent.com/4333569/65930412-a774cb80-e440-11e9-932d-b861c4cee0f5.png)
![├─](https://user-images.githubusercontent.com/4333569/65930416-aa6fbc00-e440-11e9-89c3-5ed4ef2b07de.png)
![└─](https://user-images.githubusercontent.com/4333569/65930419-aba0e900-e440-11e9-9cf7-f8f300b538ed.png)
![│](https://user-images.githubusercontent.com/4333569/65930420-acd21600-e440-11e9-8a91-5c3b2daf91ff.png)

## 動作環境
HackGen Console for Powerline Version 1.2.1
pstree Version 23.1
tree v1.7.0
Windows 10 (WSL Ubuntu 18.04.3 LTS)
Ubuntu 18.04.2 LTS (WSL から ssh 接続)

### P.S.
HackGen，大変ありがたく使わせていただいています．
環境構築のたびのフォント導入がとても簡単になってありがたいです． :)

**Comment by yuru7** [comment]
ご報告ありがとうございます。事象を確認しました。

HackGen (35版は含まない) の Console 版でのみ発生している事象のようです。ヒンティングの処理がどうも悪さをしているようです。

HackGen Console で `┬├└` を表示
![image](https://user-images.githubusercontent.com/13458509/65999508-7cd65180-e4d8-11e9-8f49-9f742272ad25.png)

ヒンティング削除後
![image](https://user-images.githubusercontent.com/13458509/65999573-99728980-e4d8-11e9-9e3a-3c22036404af.png)

時間を見つけて対処します。

## メモ

* Console 版は罫線関係のグリフを一時的に退避、Modified Hack のグリフから削除
* ヒンティング付与後、退避したグリフを merge

```
U+2534	┴	(128, 16)	┻
U+252C	┬	(136, 16)	┳
U+251C	├	(144, 16)	┣
U+253C	┼	(152, 16)	╋
U+2524	┤	(160, 16)	┫
U+2500	─	(168, 16)	━
U+2502	│	(176, 16)	┃
U+250C	┌	(192, 16)	┏
U+2510	┐	(200, 16)	┓
U+2514	└	(208, 16)	┗
U+2518	┘	(216, 16)	┛
U+2576	╶	(168, 96)	罫線短い右
U+2577	╷	(176, 96)	罫線短い下
U+2574	╴	(184, 96)	罫線短い左
U+2575	╵	(192, 96)	罫線短い上
U+253B	┻	(200, 96)	二重罫線┻
U+2533	┳	(208, 96)	二重罫線┳
U+2523	┣	(216, 96)	二重罫線┣
U+254B	╋	(224, 96)	二重罫線╋
U+252B	┫	(232, 96)	二重罫線┫
U+2501	━	(240, 96)	二重罫線━
U+2503	┃	(248, 96)	二重罫線┃
U+250F	┏	(256, 96)	二重罫線┏
U+2513	┓	(264, 96)	二重罫線┓
U+2517	┗	(272, 96)	二重罫線┗
U+251B	┛	(280, 96)	二重罫線┛
U+257A	╺	(288, 96)	二重罫線短い右
U+257B	╻	(296, 96)	二重罫線短い下
U+2578	╸	(304, 96)	二重罫線短い左
U+2579	╹	(312, 96)	二重罫線短い上
U+2537	┷	(320, 96)	複合罫線┷
U+252F	┯	(328, 96)	複合罫線┯
U+2538	┸	(336, 96)	複合罫線┸
U+2530	┰	(344, 96)	複合罫線┰
U+2520	┠	(352, 96)	複合罫線┠
U+2542	╂	(360, 96)	複合罫線╂
U+2528	┨	(368, 96)	複合罫線┨
U+251D	┝	(376, 96)	複合罫線┝
U+253F	┿	(384, 96)	複合罫線┿
U+2525	┥	(392, 96)	複合罫線┥
```

**Comment by yuru7** [comment]
v1.3.0 にて修正しました！ご確認ください。

**Comment by huyu398** [comment]
@yuru7 
早速ご対応いただきましてありがとうございます！
無事に罫線関係の文字が表示されました．
