### ISSUE TITLE
区別が付くと良さそうな文字

### ISSUE THREAD

**Issue by yuru7** [yuru7/HackGen#9]
```
ー 一 (長音記号-漢字)
へ ヘ (ひらがな-カタカナ)
ニ 二 (カタカナ-漢字)
カ 力 (カタカナ-漢字)
ロ 口 (カタカナ-漢字)
タ 夕 (カタカナ-漢字)
ト 卜 (カタカナ-漢字)
エ 工 (カタカナ-漢字)
```

**Comment by showsaitoh** [comment]
素晴らしいフォントありがとうございます。使わせていただいております！

ところで、元のHackとゼロの文字のデザインが全然違うのはなぜですか？？
元のHackの0は縦長の棒線ですがHackGenでは普通の黒丸になっています！

あと、これはリクエストです。Cascadia Codeと源柔ゴシックで日本語フォント作ってほしいです！

**Comment by yuru7** [comment]
> ところで、元のHackとゼロの文字のデザインが全然違うのはなぜですか？？

理由は2点あります。

* 半角1:全角2 幅にする際、Hack の横幅を縮小することで 0 の内側がゴチャつく
* 私の趣味

Cascadia Code も見やすそうですね。興味が向いたら検討してみます。

**Comment by kanehis** [comment]
はじめまして。Hackgen使っています。Rictyのような丸文字でないところに魅力を感じています。

Qiitaの質問欄でもよくリクエストを見かけます。@yuru7 さんが真摯に答えている点が素晴らしいと思っています。一方で、せっかくだからforkしてやって自分でやってみようよ！とも思います。
@showsaitoh さんも自分でやってみましょう！

自分もForkして、自分好みにアレンジしようとしていますが、環境構築でコケています [1]  :sweat:フォント開発はど素人なので... 
よろしければ@yuru7 さんの環境を教えていだけませんか...？どこかに書いてあって、見落としていたらすみません。

----

[1]: https://github.com/kanehis/HackGen/issues/2

1:  https://github.com/kanehis/HackGen/issues/2

**Comment by yuru7** [comment]
@kanehis 
こんにちは。意欲的で素晴らしいですね。

環境構築手順もいつか載せよう載せようと思いつつ、なかなか重い腰が上がらず…😓 とはいえ、情報提供はさせていただきたいと思っています。

issue の内容が膨れてしまうので、 #10 に質問、要望のコメントをざっくりと書けるところを用意しました。とりあえずそちらへ記載します。

**Comment by udaken** [comment]
HackGen愛用してます！

音声記号の`ʃ`(U+0283)と
積分記号の`∫`(U+222B)が区別が難しいと思います。

発音記号は全体的に区別できないグリフが多いですね。
